### PR TITLE
[wip] Add: sample.org file and basic regression test setup

### PR DESCRIPTION
**Pull request by gcentauri**
Hello! I've recently become interested in organice, and saw issue #1 . I'm curious about Clojure and thought I could give a go at writing some tests. I know Lisp and have been an Emacs user for a long time, so after watching your how-to video I was excited to get going.

There's not much here  but I wanted to get an idea if this is the right direction to go, and how to go about asserting things about the structure of the file that is actually useful.

If you have time, let me know what I can do to lend a hand!

### CODE REVIEW

**Comment by munen** [comment]
@gcentauri This is a great start, you're definitively going in the right direction! :pray: 

As for which tests to write and how to continue in general: The first epic of org-parser is to be on feature-parity with the parser from organice. Hence, it'll make sense to:

1. Duplicate the tests relating to the parser from organice
  - https://github.com/200ok-ch/organice/blob/master/src/lib/parse_org.unit.test.js
  - https://github.com/200ok-ch/organice/blob/master/src/lib/org_utils.unit.test.js
  - https://github.com/200ok-ch/organice/blob/master/src/components/OrgFile/OrgFile.unit.test.js
2. If there's a feature missing in org-parser, implement it

Imo it's a great project to get easily going with Clojure - all the while contributing to something which could become a formal specification of Org mode which in turn could potentially be huge for a bigger set of the Emacs community.

Thank you for spending time and effort on this :pray: :bowing_man:

**Comment by gcentauri** [comment]
@munen Thank you for the reply!

I'm spending some time today trying to work on this, but I think I have a bit of a gap of understanding as to how org-parser is intended to work.

I'd started with the `sample.org` file because of the issue #1  which mentioned regression tests against it, but the JS tests you pointed me to in `organice` seem to be testing some additional functionality.  `parse_org` tests are almost all testing the parse and re-export of the org file. I didn't immediately see anything in `org-parser` or `instaparse` about going the other way, from tree back to source. This would be a feature then to implement in Clojure for `org-parser`?

Additionally, does `org-parser` intend to provide functionality similar to the `org_utils` JS module?

I'll keep looking at the code and trying to understand it but any additional guidance is welcome, thank you! :bowing_man:

**Comment by munen** [comment]
@gcentauri Thanks for asking for clarification. I can see now that it's easy to interpret what I said in different ways.

So, let me back up a little.

organice is an implementation of Org mode - built for the browser and mobile devices. Hence, it needs an Org mode parser. But it needs a lot more than that. It needs semantic understanding of Org functionality, it needs to be able to change the structure through applying certain commands and in the end, it needs to save the changed stuff back into an Org file. The exporter works quite fine and has unit tests to prove it. One of the quality goals for the parser is that when it parses and re-exports an Org file, it should not change the original file. Not seeing unrelated diffs is important for the productivity of the user. It sounds trivial, but lots of alternative products do not live up to this expectation. TL;DR: organice does a lot.

org-parser has a different scope. I'll cheat a little and quote the Readme:

> To our knowledge, there is no formal specification of Org. But there is a ‘spec’ written in prose which lead to the reference implementation of Org in Emacs.

The over-arching goal of org-parser is to have a machine readable specification of the Org markup language which can be consumed by different applications and programming languages.

That's a big goal already. It's not supposed to do a whole lot more. At some point, it might learn how to serialize it's internal AST back into an Org file.

Therefore, the next steps for org-parser are:

- Get the parser on feature parity with the one from organice.
  - Hence the links to the organice repo, not for the other functionality in the files.
  - Write tests for this functionality.
- Continue implementing features from the ['prose spec'](https://orgmode.org/worg/dev/org-syntax.html).
  - Write tests for this functionality.

Both of them can be tackled in no particular order. The sample.org file pretty much resembles the functionality what organice can do. So it'll make sense to work on these features. However, it also makes sense of whatever Org feature floats your particular boat. Please feel free to pick a starting point that seems reasonable and achievable for you^^

**Comment by gcentauri** [comment]
> The over-arching goal of org-parser is to have a machine readable specification of the Org markup language which can be consumed by different applications and programming languages.

Indeed. That is what I had originally thought. I was being a bit too literal in the idea of "duplicating" the tests. I see now that the ebnf file is the main goal and that the clojure is providing the framework for testing it primarily. I had a mistaken idea that the clojure data structures being produced were going to be used directly (I saw your comment about ImmutableJS and got some wires crossed).

I'll likely close this PR or repurpose it for a smaller task as I get things figured out.  Thank you for your feedback.

**Comment by munen** [comment]
Using instaparse (and Clojure) will give any JVM or JS based language the ability to use the parser. We chose it not only for the nice syntax of the actual parser, but also for the wide reach. 

The applications using the parser will also use the produced data structures. They might transform them into something else if they need to.

**Comment by gcentauri** [comment]
I've moved focus to #7

**Pull request closed without merging**
