### PR TITLE
feat: Run `org-parser` from NodeJS and Java

### PR DESCRIPTION
**Pull request by munen**
Changes and how to run: See README.org

### CODE REVIEW

**Comment by schoettl** [comment]
As far as I understand, I cannot yet include the generated file `target/org-parser.js` in other JS files. I can call the executable from JS or from command line scripts.

Am I right?

**Comment by munen** [comment]
@schoettl The current interface of `core.cljs` is that `org-parser` will be called from the commandline with the parameter of one org file in the path which is to be parsed.

If you want to call it as a library, a public function needs to be written which takes said path as a parameter.

**Comment by schoettl** [comment]
So, I would have to add the public interface function in the same way as `(defn -main ...)` in `core.cljs`? (Similar to the parser functions which are declared in the tests, I guess.)

What do you think of this names for *the* public interface functions:
```
(defn parse-org [text] ...)   <- to parse a org string
(defn parse-org-file [path & args] ...)    <- to parse a file
```

Anything to consider regarding other target runtimes? (e.g. slurp, can that work now on JS?)

**Comment by munen** [comment]
@schoettl The interface is perfect!

Good luck with the implementation. I tried to do it quickly, too, but failed to make it compile with all dependencies. Hence, it's not included in this PR.

Some notes:

- If we run Closure optimizations other than `:none` or `:whitespace`, we need an `externs` entry for a public API
- If you also cannot get cljsbuild to work, feel free to use any other build tool like `clj deps` or `shadow cljs`

Good luck!

**Comment by schoettl** [comment]
Alright, thanks for the hints. I created a separated issue for this.

I think we can merge this PR, as it already adds the command line interface.

**Comment by munen** [comment]
@branch14  and I had a pairing session and a review. I adapted some implementation details.

Ready to merge.

**Comment by schoettl** [comment]
Nice! I'm happy that we are now able to use the parser from command line – despite its early state. I'm looking forward to work on the parser again :)

**Comment by munen** [comment]
I'm happy, too^^

If you can already start making some use of it, that would be great, of course(;

**Pull request merged**
